#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["LSSD.Lunch.WebManager/LSSD.Lunch.WebManager.csproj", "LSSD.Lunch.WebManager/"]
COPY ["LSSD.Lunch.Core/Core.csproj", "LSSD.Lunch.Core/"]
RUN dotnet restore "LSSD.Lunch.WebManager/LSSD.Lunch.WebManager.csproj"
COPY . .
WORKDIR "/src/LSSD.Lunch.WebManager"
RUN dotnet build "LSSD.Lunch.WebManager.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "LSSD.Lunch.WebManager.csproj" -c Release -o /app/publish

FROM base AS final

# install System.Drawing native dependencies
RUN apt-get update \
    && apt-get install -y --allow-unauthenticated \
        libc6-dev \
        libgdiplus \
        libx11-dev \
     && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "LSSD.Lunch.WebManager.dll"]